/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BlindReview {
  export type CategoryWeightsStruct = {
    problemSolving: BigNumberish;
    technicalDepth: BigNumberish;
    communication: BigNumberish;
    collaboration: BigNumberish;
    cultureGrowth: BigNumberish;
  };

  export type CategoryWeightsStructOutput = [
    problemSolving: bigint,
    technicalDepth: bigint,
    communication: bigint,
    collaboration: bigint,
    cultureGrowth: bigint
  ] & {
    problemSolving: bigint;
    technicalDepth: bigint;
    communication: bigint;
    collaboration: bigint;
    cultureGrowth: bigint;
  };

  export type AutoAdvanceRuleStruct = {
    enabled: boolean;
    passThreshold: BigNumberish;
    failThreshold: BigNumberish;
    passAction: BigNumberish;
    failAction: BigNumberish;
  };

  export type AutoAdvanceRuleStructOutput = [
    enabled: boolean,
    passThreshold: bigint,
    failThreshold: bigint,
    passAction: bigint,
    failAction: bigint
  ] & {
    enabled: boolean;
    passThreshold: bigint;
    failThreshold: bigint;
    passAction: bigint;
    failAction: bigint;
  };
}

export interface BlindReviewInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "CATEGORY_COUNT"
      | "MAX_EXTENSION"
      | "MAX_REVIEWERS"
      | "MAX_ROUNDS_PER_CANDIDATE"
      | "MIN_DEADLINE_GAP"
      | "MIN_REVIEWERS"
      | "NUM_TAGS"
      | "cancelReview"
      | "confidentialProtocolId"
      | "createReview"
      | "extendDeadline"
      | "getAutoAdvanceRule"
      | "getCandidateRounds"
      | "getCategoryWeights"
      | "getMyTagMask"
      | "getRevealHandles"
      | "getRevealedScores"
      | "getReviewSummary"
      | "getReviewers"
      | "hasReviewerSubmitted"
      | "isInvitedReviewer"
      | "nextReviewId"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "replaceReviewer"
      | "requestReveal"
      | "submitRevealedScores"
      | "submitScores"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutoAdvanceTriggered"
      | "DeadlineExtended"
      | "OwnershipTransferred"
      | "Paused"
      | "PublicDecryptionVerified"
      | "RevealRequested"
      | "Revealed"
      | "ReviewCancelled"
      | "ReviewCreated"
      | "ReviewerReplaced"
      | "ScoreSubmitted"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CATEGORY_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EXTENSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_REVIEWERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ROUNDS_PER_CANDIDATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_DEADLINE_GAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_REVIEWERS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "NUM_TAGS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelReview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createReview",
    values: [
      string,
      string,
      AddressLike[],
      BigNumberish,
      BlindReview.CategoryWeightsStruct,
      BlindReview.AutoAdvanceRuleStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "extendDeadline",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAutoAdvanceRule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidateRounds",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCategoryWeights",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyTagMask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRevealHandles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRevealedScores",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReviewSummary",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReviewers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReviewerSubmitted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInvitedReviewer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextReviewId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "replaceReviewer",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestReveal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRevealedScores",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitScores",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CATEGORY_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EXTENSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REVIEWERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ROUNDS_PER_CANDIDATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DEADLINE_GAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_REVIEWERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "NUM_TAGS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAutoAdvanceRule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidateRounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCategoryWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyTagMask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRevealHandles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRevealedScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReviewSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReviewers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReviewerSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInvitedReviewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextReviewId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replaceReviewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRevealedScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace AutoAdvanceTriggeredEvent {
  export type InputTuple = [
    reviewId: BigNumberish,
    action: BigNumberish,
    weightedScore: BigNumberish
  ];
  export type OutputTuple = [
    reviewId: bigint,
    action: bigint,
    weightedScore: bigint
  ];
  export interface OutputObject {
    reviewId: bigint;
    action: bigint;
    weightedScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeadlineExtendedEvent {
  export type InputTuple = [
    reviewId: BigNumberish,
    oldDeadline: BigNumberish,
    newDeadline: BigNumberish,
    admin: AddressLike
  ];
  export type OutputTuple = [
    reviewId: bigint,
    oldDeadline: bigint,
    newDeadline: bigint,
    admin: string
  ];
  export interface OutputObject {
    reviewId: bigint;
    oldDeadline: bigint;
    newDeadline: bigint;
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicDecryptionVerifiedEvent {
  export type InputTuple = [
    handlesList: BytesLike[],
    abiEncodedCleartexts: BytesLike
  ];
  export type OutputTuple = [
    handlesList: string[],
    abiEncodedCleartexts: string
  ];
  export interface OutputObject {
    handlesList: string[];
    abiEncodedCleartexts: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevealRequestedEvent {
  export type InputTuple = [reviewId: BigNumberish, handles: BytesLike[]];
  export type OutputTuple = [reviewId: bigint, handles: string[]];
  export interface OutputObject {
    reviewId: bigint;
    handles: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevealedEvent {
  export type InputTuple = [
    reviewId: BigNumberish,
    sumProblemSolving: BigNumberish,
    sumTechnicalDepth: BigNumberish,
    sumCommunication: BigNumberish,
    sumCollaboration: BigNumberish,
    sumCultureGrowth: BigNumberish,
    sumSqProblemSolving: BigNumberish,
    sumSqTechnicalDepth: BigNumberish,
    sumSqCommunication: BigNumberish,
    sumSqCollaboration: BigNumberish,
    sumSqCultureGrowth: BigNumberish,
    reviewerCount: BigNumberish,
    tagCounts: BigNumberish[]
  ];
  export type OutputTuple = [
    reviewId: bigint,
    sumProblemSolving: bigint,
    sumTechnicalDepth: bigint,
    sumCommunication: bigint,
    sumCollaboration: bigint,
    sumCultureGrowth: bigint,
    sumSqProblemSolving: bigint,
    sumSqTechnicalDepth: bigint,
    sumSqCommunication: bigint,
    sumSqCollaboration: bigint,
    sumSqCultureGrowth: bigint,
    reviewerCount: bigint,
    tagCounts: bigint[]
  ];
  export interface OutputObject {
    reviewId: bigint;
    sumProblemSolving: bigint;
    sumTechnicalDepth: bigint;
    sumCommunication: bigint;
    sumCollaboration: bigint;
    sumCultureGrowth: bigint;
    sumSqProblemSolving: bigint;
    sumSqTechnicalDepth: bigint;
    sumSqCommunication: bigint;
    sumSqCollaboration: bigint;
    sumSqCultureGrowth: bigint;
    reviewerCount: bigint;
    tagCounts: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewCancelledEvent {
  export type InputTuple = [
    reviewId: BigNumberish,
    admin: AddressLike,
    submittedCountAtCancellation: BigNumberish
  ];
  export type OutputTuple = [
    reviewId: bigint,
    admin: string,
    submittedCountAtCancellation: bigint
  ];
  export interface OutputObject {
    reviewId: bigint;
    admin: string;
    submittedCountAtCancellation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewCreatedEvent {
  export type InputTuple = [
    reviewId: BigNumberish,
    admin: AddressLike,
    candidateRef: string,
    role: string,
    roundNumber: BigNumberish,
    reviewerCount: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    reviewId: bigint,
    admin: string,
    candidateRef: string,
    role: string,
    roundNumber: bigint,
    reviewerCount: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    reviewId: bigint;
    admin: string;
    candidateRef: string;
    role: string;
    roundNumber: bigint;
    reviewerCount: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewerReplacedEvent {
  export type InputTuple = [
    reviewId: BigNumberish,
    oldReviewer: AddressLike,
    newReviewer: AddressLike,
    admin: AddressLike
  ];
  export type OutputTuple = [
    reviewId: bigint,
    oldReviewer: string,
    newReviewer: string,
    admin: string
  ];
  export interface OutputObject {
    reviewId: bigint;
    oldReviewer: string;
    newReviewer: string;
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreSubmittedEvent {
  export type InputTuple = [
    reviewId: BigNumberish,
    reviewer: AddressLike,
    submittedCount: BigNumberish,
    reviewerCount: BigNumberish
  ];
  export type OutputTuple = [
    reviewId: bigint,
    reviewer: string,
    submittedCount: bigint,
    reviewerCount: bigint
  ];
  export interface OutputObject {
    reviewId: bigint;
    reviewer: string;
    submittedCount: bigint;
    reviewerCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlindReview extends BaseContract {
  connect(runner?: ContractRunner | null): BlindReview;
  waitForDeployment(): Promise<this>;

  interface: BlindReviewInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  CATEGORY_COUNT: TypedContractMethod<[], [bigint], "view">;

  MAX_EXTENSION: TypedContractMethod<[], [bigint], "view">;

  MAX_REVIEWERS: TypedContractMethod<[], [bigint], "view">;

  MAX_ROUNDS_PER_CANDIDATE: TypedContractMethod<[], [bigint], "view">;

  MIN_DEADLINE_GAP: TypedContractMethod<[], [bigint], "view">;

  MIN_REVIEWERS: TypedContractMethod<[], [bigint], "view">;

  NUM_TAGS: TypedContractMethod<[], [bigint], "view">;

  cancelReview: TypedContractMethod<
    [reviewId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createReview: TypedContractMethod<
    [
      candidateRef: string,
      role: string,
      reviewerList: AddressLike[],
      deadline: BigNumberish,
      weights: BlindReview.CategoryWeightsStruct,
      advanceRule: BlindReview.AutoAdvanceRuleStruct
    ],
    [bigint],
    "nonpayable"
  >;

  extendDeadline: TypedContractMethod<
    [reviewId: BigNumberish, newDeadline: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAutoAdvanceRule: TypedContractMethod<
    [reviewId: BigNumberish],
    [BlindReview.AutoAdvanceRuleStructOutput],
    "view"
  >;

  getCandidateRounds: TypedContractMethod<
    [candidateRef: string],
    [bigint[]],
    "view"
  >;

  getCategoryWeights: TypedContractMethod<
    [reviewId: BigNumberish],
    [BlindReview.CategoryWeightsStructOutput],
    "view"
  >;

  getMyTagMask: TypedContractMethod<[reviewId: BigNumberish], [bigint], "view">;

  getRevealHandles: TypedContractMethod<
    [reviewId: BigNumberish],
    [string[]],
    "view"
  >;

  getRevealedScores: TypedContractMethod<
    [reviewId: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint[]
      ] & {
        sumProblemSolving: bigint;
        sumTechnicalDepth: bigint;
        sumCommunication: bigint;
        sumCollaboration: bigint;
        sumCultureGrowth: bigint;
        sumSqProblemSolving: bigint;
        sumSqTechnicalDepth: bigint;
        sumSqCommunication: bigint;
        sumSqCollaboration: bigint;
        sumSqCultureGrowth: bigint;
        reviewerCount: bigint;
        tagCounts: bigint[];
      }
    ],
    "view"
  >;

  getReviewSummary: TypedContractMethod<
    [reviewId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        admin: string;
        candidateRef: string;
        role: string;
        roundNumber: bigint;
        deadline: bigint;
        reviewerCount: bigint;
        submittedCount: bigint;
        status: bigint;
        extensionUsed: boolean;
      }
    ],
    "view"
  >;

  getReviewers: TypedContractMethod<
    [reviewId: BigNumberish],
    [string[]],
    "view"
  >;

  hasReviewerSubmitted: TypedContractMethod<
    [reviewId: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;

  isInvitedReviewer: TypedContractMethod<
    [reviewId: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;

  nextReviewId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  replaceReviewer: TypedContractMethod<
    [
      reviewId: BigNumberish,
      oldReviewer: AddressLike,
      newReviewer: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  requestReveal: TypedContractMethod<
    [reviewId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitRevealedScores: TypedContractMethod<
    [
      reviewId: BigNumberish,
      abiEncodedClearValues: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitScores: TypedContractMethod<
    [
      reviewId: BigNumberish,
      problemSolving: BytesLike,
      technicalDepth: BytesLike,
      communication: BytesLike,
      collaboration: BytesLike,
      cultureGrowth: BytesLike,
      inputProof: BytesLike,
      tagMask: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CATEGORY_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_EXTENSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REVIEWERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_ROUNDS_PER_CANDIDATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DEADLINE_GAP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_REVIEWERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NUM_TAGS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelReview"
  ): TypedContractMethod<[reviewId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createReview"
  ): TypedContractMethod<
    [
      candidateRef: string,
      role: string,
      reviewerList: AddressLike[],
      deadline: BigNumberish,
      weights: BlindReview.CategoryWeightsStruct,
      advanceRule: BlindReview.AutoAdvanceRuleStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "extendDeadline"
  ): TypedContractMethod<
    [reviewId: BigNumberish, newDeadline: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAutoAdvanceRule"
  ): TypedContractMethod<
    [reviewId: BigNumberish],
    [BlindReview.AutoAdvanceRuleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCandidateRounds"
  ): TypedContractMethod<[candidateRef: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getCategoryWeights"
  ): TypedContractMethod<
    [reviewId: BigNumberish],
    [BlindReview.CategoryWeightsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyTagMask"
  ): TypedContractMethod<[reviewId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRevealHandles"
  ): TypedContractMethod<[reviewId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRevealedScores"
  ): TypedContractMethod<
    [reviewId: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint[]
      ] & {
        sumProblemSolving: bigint;
        sumTechnicalDepth: bigint;
        sumCommunication: bigint;
        sumCollaboration: bigint;
        sumCultureGrowth: bigint;
        sumSqProblemSolving: bigint;
        sumSqTechnicalDepth: bigint;
        sumSqCommunication: bigint;
        sumSqCollaboration: bigint;
        sumSqCultureGrowth: bigint;
        reviewerCount: bigint;
        tagCounts: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReviewSummary"
  ): TypedContractMethod<
    [reviewId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        admin: string;
        candidateRef: string;
        role: string;
        roundNumber: bigint;
        deadline: bigint;
        reviewerCount: bigint;
        submittedCount: bigint;
        status: bigint;
        extensionUsed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReviewers"
  ): TypedContractMethod<[reviewId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasReviewerSubmitted"
  ): TypedContractMethod<
    [reviewId: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isInvitedReviewer"
  ): TypedContractMethod<
    [reviewId: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextReviewId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "replaceReviewer"
  ): TypedContractMethod<
    [
      reviewId: BigNumberish,
      oldReviewer: AddressLike,
      newReviewer: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestReveal"
  ): TypedContractMethod<[reviewId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitRevealedScores"
  ): TypedContractMethod<
    [
      reviewId: BigNumberish,
      abiEncodedClearValues: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitScores"
  ): TypedContractMethod<
    [
      reviewId: BigNumberish,
      problemSolving: BytesLike,
      technicalDepth: BytesLike,
      communication: BytesLike,
      collaboration: BytesLike,
      cultureGrowth: BytesLike,
      inputProof: BytesLike,
      tagMask: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AutoAdvanceTriggered"
  ): TypedContractEvent<
    AutoAdvanceTriggeredEvent.InputTuple,
    AutoAdvanceTriggeredEvent.OutputTuple,
    AutoAdvanceTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "DeadlineExtended"
  ): TypedContractEvent<
    DeadlineExtendedEvent.InputTuple,
    DeadlineExtendedEvent.OutputTuple,
    DeadlineExtendedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PublicDecryptionVerified"
  ): TypedContractEvent<
    PublicDecryptionVerifiedEvent.InputTuple,
    PublicDecryptionVerifiedEvent.OutputTuple,
    PublicDecryptionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RevealRequested"
  ): TypedContractEvent<
    RevealRequestedEvent.InputTuple,
    RevealRequestedEvent.OutputTuple,
    RevealRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Revealed"
  ): TypedContractEvent<
    RevealedEvent.InputTuple,
    RevealedEvent.OutputTuple,
    RevealedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewCancelled"
  ): TypedContractEvent<
    ReviewCancelledEvent.InputTuple,
    ReviewCancelledEvent.OutputTuple,
    ReviewCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ReviewCreated"
  ): TypedContractEvent<
    ReviewCreatedEvent.InputTuple,
    ReviewCreatedEvent.OutputTuple,
    ReviewCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewerReplaced"
  ): TypedContractEvent<
    ReviewerReplacedEvent.InputTuple,
    ReviewerReplacedEvent.OutputTuple,
    ReviewerReplacedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreSubmitted"
  ): TypedContractEvent<
    ScoreSubmittedEvent.InputTuple,
    ScoreSubmittedEvent.OutputTuple,
    ScoreSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AutoAdvanceTriggered(uint256,uint8,uint32)": TypedContractEvent<
      AutoAdvanceTriggeredEvent.InputTuple,
      AutoAdvanceTriggeredEvent.OutputTuple,
      AutoAdvanceTriggeredEvent.OutputObject
    >;
    AutoAdvanceTriggered: TypedContractEvent<
      AutoAdvanceTriggeredEvent.InputTuple,
      AutoAdvanceTriggeredEvent.OutputTuple,
      AutoAdvanceTriggeredEvent.OutputObject
    >;

    "DeadlineExtended(uint256,uint256,uint256,address)": TypedContractEvent<
      DeadlineExtendedEvent.InputTuple,
      DeadlineExtendedEvent.OutputTuple,
      DeadlineExtendedEvent.OutputObject
    >;
    DeadlineExtended: TypedContractEvent<
      DeadlineExtendedEvent.InputTuple,
      DeadlineExtendedEvent.OutputTuple,
      DeadlineExtendedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PublicDecryptionVerified(bytes32[],bytes)": TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
    PublicDecryptionVerified: TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;

    "RevealRequested(uint256,bytes32[10])": TypedContractEvent<
      RevealRequestedEvent.InputTuple,
      RevealRequestedEvent.OutputTuple,
      RevealRequestedEvent.OutputObject
    >;
    RevealRequested: TypedContractEvent<
      RevealRequestedEvent.InputTuple,
      RevealRequestedEvent.OutputTuple,
      RevealRequestedEvent.OutputObject
    >;

    "Revealed(uint256,uint16,uint16,uint16,uint16,uint16,uint16,uint16,uint16,uint16,uint16,uint256,uint8[8])": TypedContractEvent<
      RevealedEvent.InputTuple,
      RevealedEvent.OutputTuple,
      RevealedEvent.OutputObject
    >;
    Revealed: TypedContractEvent<
      RevealedEvent.InputTuple,
      RevealedEvent.OutputTuple,
      RevealedEvent.OutputObject
    >;

    "ReviewCancelled(uint256,address,uint8)": TypedContractEvent<
      ReviewCancelledEvent.InputTuple,
      ReviewCancelledEvent.OutputTuple,
      ReviewCancelledEvent.OutputObject
    >;
    ReviewCancelled: TypedContractEvent<
      ReviewCancelledEvent.InputTuple,
      ReviewCancelledEvent.OutputTuple,
      ReviewCancelledEvent.OutputObject
    >;

    "ReviewCreated(uint256,address,string,string,uint8,uint256,uint256)": TypedContractEvent<
      ReviewCreatedEvent.InputTuple,
      ReviewCreatedEvent.OutputTuple,
      ReviewCreatedEvent.OutputObject
    >;
    ReviewCreated: TypedContractEvent<
      ReviewCreatedEvent.InputTuple,
      ReviewCreatedEvent.OutputTuple,
      ReviewCreatedEvent.OutputObject
    >;

    "ReviewerReplaced(uint256,address,address,address)": TypedContractEvent<
      ReviewerReplacedEvent.InputTuple,
      ReviewerReplacedEvent.OutputTuple,
      ReviewerReplacedEvent.OutputObject
    >;
    ReviewerReplaced: TypedContractEvent<
      ReviewerReplacedEvent.InputTuple,
      ReviewerReplacedEvent.OutputTuple,
      ReviewerReplacedEvent.OutputObject
    >;

    "ScoreSubmitted(uint256,address,uint8,uint256)": TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
    ScoreSubmitted: TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
